#!/usr/bin/env bash
# Replace a line with multiple lines with sed

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name_;\n\trewrite^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4a;"
sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
