#!/usr/bin/env bash
# Configures a brand new Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow

# Create directory for web content
sudo mkdir -p /var/www/html

# Set permissions for web directory
sudo chmod -R 755 /var/www

# Create index.html file
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create 404.html file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Define replacement string for Nginx configuration
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4a permanent;"

# Replace server_name in Nginx configuration file
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Define replacement string for Nginx configuration
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

# Replace listen directive in Nginx configuration file
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
