#!/usr/bin/env bash
# The type of network a computer in local is connected to.
# The type of network that could connect an office in one building to another office in a building a few streets away.
# The network you use when you browse www.google.com from your smartphone (not connected to the Wifi).

3
2
1
