#!/usr/bin/env bash
# Script that creates a file, displays various messages, deletes the file and terminates itself when receiving SIGQUIT/SIGTERM signal.

echo $$ > /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

while true
do
	echo "To infinity and beyond"
done

