#!/usr/bin/env bash
# Script that displays the username, user id, Home directory path for the user of the file /etc/passwd.

file="/etc/passwd"
while IFS= read -r line; do
	echo "$line" | cut -d":" -f1,3,6
done < "$file"
