#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username password uid gid user_info home_dir shell
do
	echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
