#!/usr/bin/env bash
# Script that displays content of the current directory, in a list format, where only the part of the name after the first dash is displayed

myList=$(ls)

for file in $myList; do
	echo "$file" | cut -d '-' -f2
done
