#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

LOCALHOST_IP="127.0.0.2"
FACEBOOK_IP="8.8.8.8"

cat << DONE > my_hosts
127.0.0.2	localhost
${LOCALHOST_IP}	localhost
${FACEBOOK_IP}	facebook.com
DONE

sudo cp my_hosts /etc/hosts
