#!/usr/bin/env bash
# Nginx to run as the nginx user
# nginx must be listening on all active IPs on port 8080

pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod a+r /etc/nginx/nginx.conf
chmod u+w /etc/nginx/nginx.conf
sed -i 's|80 default_server|8080 default_server|g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
